<map id="BRepFeat_MakeLinearForm" name="BRepFeat_MakeLinearForm">
<area shape="rect" id="node2" href="$class_b_rep_feat___rib_slot.html" title="Provides functions to build mechanical features. Mechanical features include ribs &#45; protrusions and g..." alt="" coords="35,155,164,181"/>
<area shape="rect" id="node3" href="$class_b_rep_builder_a_p_i___make_shape.html" title="This is the root class for all shape constructions. It stores the result. " alt="" coords="5,80,195,107"/>
<area shape="rect" id="node4" href="$class_b_rep_builder_a_p_i___command.html" title="Root class for all commands in BRepBuilderAPI. " alt="" coords="9,5,191,32"/>
</map>
